from datetime import UTC, datetime, timedelta

CAFE = {"id": "cafe-linden", "name": "Linden & Steam", "open": True, "source": "synthetic fixture", "updated_at": datetime.now(UTC).isoformat(), "status": "demo"}
MENU = [
    {"id": "iced-matcha", "name": "Iced Matcha Oat Latte", "price": 290, "cold": True, "vegetarian": True, "available": True, "stock_units": 2, "low_stock_threshold": 5, "ingredients": ["matcha", "oat milk", "ice"], "allergens": [], "cross_contact": "unknown", "source": "synthetic menu fixture", "source_id": "menu-101", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 7, "tags": ["oat_milk", "quiet"]},
    {"id": "cold-brew", "name": "Vanilla Cold Brew", "price": 240, "cold": True, "vegetarian": True, "available": True, "stock_units": 18, "low_stock_threshold": 5, "ingredients": ["coffee", "milk", "vanilla"], "allergens": ["milk"], "cross_contact": "clear", "source": "synthetic menu fixture", "source_id": "menu-102", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 5, "tags": ["low_sweetness"]},
    {"id": "mocha", "name": "Hazelnut Mocha Frappe", "price": 330, "cold": True, "vegetarian": False, "available": True, "stock_units": 6, "low_stock_threshold": 5, "ingredients": ["coffee", "milk", "peanut praline"], "allergens": ["milk", "peanuts"], "cross_contact": "unknown", "source": "synthetic menu fixture", "source_id": "menu-103", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 9, "tags": ["caramel"]},
    {"id": "espresso", "name": "Double Espresso", "price": 170, "cold": False, "vegetarian": True, "available": True, "stock_units": 20, "low_stock_threshold": 4, "ingredients": ["espresso coffee"], "allergens": [], "cross_contact": "clear", "source": "synthetic menu fixture", "source_id": "menu-104", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 3, "tags": ["coffee", "espresso", "hot"]},
    {"id": "americano", "name": "Hot Americano", "price": 190, "cold": False, "vegetarian": True, "available": True, "stock_units": 16, "low_stock_threshold": 4, "ingredients": ["espresso coffee", "hot water"], "allergens": [], "cross_contact": "clear", "source": "synthetic menu fixture", "source_id": "menu-105", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 4, "tags": ["coffee", "americano", "hot"]},
    {"id": "hot-latte", "name": "Hot Oat Latte", "price": 260, "cold": False, "vegetarian": True, "available": True, "stock_units": 12, "low_stock_threshold": 4, "ingredients": ["espresso coffee", "oat milk"], "allergens": [], "cross_contact": "unknown", "source": "synthetic menu fixture", "source_id": "menu-106", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 6, "tags": ["coffee", "latte", "oat_milk", "hot"]},
    {"id": "cappuccino", "name": "Cappuccino", "price": 240, "cold": False, "vegetarian": True, "available": True, "stock_units": 10, "low_stock_threshold": 4, "ingredients": ["espresso coffee", "milk"], "allergens": ["milk"], "cross_contact": "unknown", "source": "synthetic menu fixture", "source_id": "menu-107", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 5, "tags": ["coffee", "cappuccino", "hot"]},
    {"id": "masala-chai", "name": "Masala Chai", "price": 180, "cold": False, "vegetarian": True, "available": True, "stock_units": 14, "low_stock_threshold": 4, "ingredients": ["black tea", "milk", "spices"], "allergens": ["milk"], "cross_contact": "unknown", "source": "synthetic menu fixture", "source_id": "menu-108", "updated_at": datetime.now(UTC).isoformat(), "status": "demo", "prep": 5, "tags": ["tea", "chai", "hot"]},
]
QUEUE = {"active_orders": 3, "estimated_wait_minutes": 8, "source": "synthetic queue fixture", "updated_at": datetime.now(UTC).isoformat(), "status": "demo"}
ZONES = [{"name": "Window quiet zone", "occupancy": "low", "seats": 4, "status": "demo", "source": "synthetic occupancy fixture"}, {"name": "Community table", "occupancy": "high", "seats": 0, "status": "demo", "source": "synthetic occupancy fixture"}]
